version: '3.3'
services:
  web:
    image: apap-registry.cs.ui.ac.id/maritza.rahayu/apap-102
    restart: always
    ports:
      - "10102:8080"
    volumes:
      - ./file-storage:/file-storage
      - ./log:/log
    env_file:
      - bacabaca/.env
    depends_on:
      - db
    networks:
      - frontend-network
      - backend-network

  db:
    image: postgres:14-alpine
    ports:
      - '15102:5432'
    restart: 'no'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=secret99
    volumes:
      - db:/var/lib/postgresql/data
    networks:
      - backend-network

volumes:
  db:

networks:
  frontend-network:
    driver: bridge
  backend-network:
    driver: bridge